version: '3'

networks:
  jenkins_network:
    driver: bridge

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-blueocean
    networks:
      - jenkins_network
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./run_env/jenkins_home:/var/jenkins_home
      - ./run_env/certs:/certs/client:ro
    restart: on-failure
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    ports:
      - 127.0.0.1:2376:2375
    restart: always
