version: '3'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ./run_env/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure