version: '3'

networks:
  jenkins:
    driver: bridge

services:
  docker:
    container_name: docker
    image: docker:dind
    volumes:
      - /run_env/jenkins_home:/var/jenkins_home
    ports:
      - 2376:2376
    privileged: true
    networks:
      - jenkins
  jenkins:
    container_name: jenkins
    user: root
    build:
      context: jenkins/
    restart: on-failure
    networks:
      - jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - /run_env/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  